START_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
MODEL_WIDTH = 480
MODEL_HEIGHT = 288
MARKER_RADIUS = 25
MARKER_DIAMETER = 2 * MARKER_RADIUS
CORNER_KEYS = ["h1", "a1", "a8", "h8"]
SQUARE_SIZE = 128
BOARD_SIZE = 8 * SQUARE_SIZE

